#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Print a coloured line across the width of the terminal.
# ──────────────────────────────────────────────────────────────────────────────

print_help() {
    cat <<EOF
Usage: termline [FLAG] [ARG]

  Print a coloured line across the width of the terminal.

  Color names:

    • black           • bright-black (grey, gray)
    • red             • bright-red
    • green           • bright-green
    • yellow          • bright-yellow
    • blue            • bright-blue
    • magenta         • bright-magenta
    • cyan            • bright-cyan
    • white           • bright-white

Arguments:
  [color]           A named colour or a colour code between 0 and 255.

Flags:
  -h, --help        Print this help text and exit.
EOF
}

# Terminal width.
cols=$(tput cols)

# Try to print a line for each argument.
for arg in "$@"; do

    # Set the foreground color.
    case "$arg" in
        --help|-h)
            print_help
            exit 0
            ;;
        black)
            echo -ne "\e[30m"
            ;;
        red)
            echo -ne "\e[31m"
            ;;
        green)
            echo -ne "\e[32m"
            ;;
        yellow)
            echo -ne "\e[33m"
            ;;
        blue)
            echo -ne "\e[34m"
            ;;
        magenta)
            echo -ne "\e[35m"
            ;;
        cyan)
            echo -ne "\e[36m"
            ;;
        white)
            echo -ne "\e[37m"
            ;;
        bright-black|grey|gray)
            echo -ne "\e[90m"
            ;;
        bright-red)
            echo -ne "\e[91m"
            ;;
        bright-green)
            echo -ne "\e[92m"
            ;;
        bright-yellow)
            echo -ne "\e[93m"
            ;;
        bright-blue)
            echo -ne "\e[94m"
            ;;
        bright-magenta)
            echo -ne "\e[95m"
            ;;
        bright-cyan)
            echo -ne "\e[96m"
            ;;
        bright-white)
            echo -ne "\e[97m"
            ;;
        "")
            ;;
        *)
            echo -ne "\e[38;5;${arg}m"
            ;;
    esac

    # Print the line.
    for (( i=0; i<$cols; i++ )); do
        echo -n "─"
    done
    echo

    # Reset the foreground colour to its default.
    if test -n "$arg"; then
        echo -ne "\e[39m"
    fi
done

# If we have no arguments, use the default color.
if test "$#" -eq 0; then
    for (( i=0; i<$cols; i++ )); do
        echo -n "─"
    done
    echo
fi
